---
deployment:
  tasks:
    - export DEPLOYPATH=/home1/lancerod/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp css/stylesheet.css $DEPLOYPATH
    - /bin/cp js/index.js $DEPLOYPATH
    - /bin/cp images $DEPLOYPATH
